[[runners]]
  name = "your-runner-name"
  url = "https://gitlab.com/"
  token = "your-registration-token"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_entrypoint_overwrite = false
    volumes = ["/cache"]
    shm_size = 0
