version: "3"
services:
  web:
    image: your-image-name:latest
    ports:
      - "3000:3000"
    networks:
      - frontend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - frontend

networks:
  frontend:
